# Generated by Django 4.0 on 2021-12-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='None', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('query', models.TextField()),
            ],
        ),
    ]
